#!/usr/bin/env node
// ================================================================
// ART GALLERY — Interactive Setup Script
// ================================================================
// Usage: node scripts/setup.mjs
// This script will:
//   1. Ask for your admin username & password
//   2. Hash the password with bcrypt (never stored in plain text)
//   3. Generate a cryptographically secure NEXTAUTH_SECRET
//   4. Create a .env.local file with all values
// ================================================================

import { createInterface } from 'readline';
import { randomBytes } from 'crypto';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { createRequire } from 'module';
import { execSync } from 'child_process';

const require = createRequire(import.meta.url);

// Ensure bcryptjs is available
function ensureBcryptjs() {
  try {
    return require('bcryptjs');
  } catch {
    console.log('Installing bcryptjs for password hashing...');
    execSync('npm install bcryptjs', { stdio: 'inherit' });
    return require('bcryptjs');
  }
}

const rl = createInterface({ input: process.stdin, output: process.stdout });

const question = (prompt) =>
  new Promise((resolve) => rl.question(prompt, resolve));

const hiddenQuestion = (prompt) =>
  new Promise((resolve) => {
    process.stdout.write(prompt);
    const stdin = process.openStdin();
    const onData = (data) => {
      stdin.pause();
      stdin.removeListener('data', onData);
      process.stdout.write('\n');
      resolve(data.toString().trim());
    };
    stdin.on('data', onData);
    stdin.resume();
  });

async function main() {
  console.log('\n\x1b[33m╔════════════════════════════════════════╗\x1b[0m');
  console.log('\x1b[33m║   Art Gallery — Environment Setup      ║\x1b[0m');
  console.log('\x1b[33m╚════════════════════════════════════════╝\x1b[0m\n');

  if (existsSync('.env.local')) {
    const overwrite = await question(
      '\x1b[31m⚠  .env.local already exists. Overwrite? (y/N): \x1b[0m'
    );
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Aborted. Your existing .env.local was not changed.');
      rl.close();
      return;
    }
  }

  const example = readFileSync('.env.example', 'utf-8');

  console.log('\x1b[36m--- Admin Credentials ---\x1b[0m');
  const adminUsername = await question('Admin username (default: admin): ');
  const adminPassword = await question('Admin password: ');

  if (!adminPassword || adminPassword.length < 8) {
    console.error('\x1b[31mError: Password must be at least 8 characters.\x1b[0m');
    rl.close();
    return;
  }

  console.log('\nHashing password with bcrypt (cost factor 12)...');
  const bcrypt = ensureBcryptjs();
  const hash = await bcrypt.hash(adminPassword, 12);
  console.log('\x1b[32m✓ Password hashed\x1b[0m');

  console.log('\nGenerating NEXTAUTH_SECRET...');
  const secret = randomBytes(32).toString('hex');
  console.log('\x1b[32m✓ Secret generated\x1b[0m');

  console.log('\n\x1b[36m--- Email (Gmail SMTP) ---\x1b[0m');
  console.log('You need a Gmail App Password (not your regular password).');
  console.log('Get one at: https://myaccount.google.com/apppasswords\n');
  const smtpUser = await question('Your Gmail address: ');
  const smtpPass = await question('Gmail App Password (16 chars): ');
  const emailFrom = await question(`Display name (e.g. "My Gallery <${smtpUser}>"): `);

  console.log('\n\x1b[36m--- Cloudinary (Image Storage) ---\x1b[0m');
  console.log('Sign up free at: https://cloudinary.com\n');
  const cloudName = await question('Cloudinary Cloud Name: ');
  const cloudApiKey = await question('Cloudinary API Key: ');
  const cloudApiSecret = await question('Cloudinary API Secret: ');

  console.log('\n\x1b[36m--- Database ---\x1b[0m');
  console.log('Sign up free at: https://neon.tech');
  console.log('Create a project → copy the connection string\n');
  const databaseUrl = await question('Neon DATABASE_URL: ');

  console.log('\n\x1b[36m--- Site Config ---\x1b[0m');
  const siteName = await question('Gallery name (e.g. "Elena Reyes Studio"): ');
  const siteTagline = await question('Tagline (e.g. "Original Art. Timeless Stories."): ');
  const siteUrl = await question('Production URL (e.g. https://mysite.vercel.app): ');

  rl.close();

  const envContent = `# ================================================================
# ART GALLERY — LOCAL ENVIRONMENT
# Generated by scripts/setup.mjs on ${new Date().toISOString()}
# ================================================================

DATABASE_URL="${databaseUrl}"

NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:3000"

ADMIN_USERNAME="${adminUsername || 'admin'}"
ADMIN_PASSWORD_HASH="${hash}"

SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_SECURE="false"
SMTP_USER="${smtpUser}"
SMTP_PASS="${smtpPass}"
EMAIL_TO="${smtpUser}"
EMAIL_FROM="${emailFrom || `Gallery <${smtpUser}>`}"

CLOUDINARY_CLOUD_NAME="${cloudName}"
CLOUDINARY_API_KEY="${cloudApiKey}"
CLOUDINARY_API_SECRET="${cloudApiSecret}"
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="${cloudName}"

NEXT_PUBLIC_SITE_NAME="${siteName || 'Art Gallery'}"
NEXT_PUBLIC_SITE_TAGLINE="${siteTagline || 'Original Art. Timeless Stories.'}"
NEXT_PUBLIC_SITE_URL="${siteUrl || 'http://localhost:3000'}"
`;

  writeFileSync('.env.local', envContent);

  console.log('\n\x1b[32m╔════════════════════════════════════════╗\x1b[0m');
  console.log('\x1b[32m║   ✓ .env.local created successfully!   ║\x1b[0m');
  console.log('\x1b[32m╚════════════════════════════════════════╝\x1b[0m\n');

  console.log('Next steps:');
  console.log('  1. npx prisma db push     — Create database tables');
  console.log('  2. npx prisma db seed     — Add sample artworks');
  console.log('  3. npm run dev            — Start development server');
  console.log('\n\x1b[33m⚠  For Vercel deployment, add all these variables in:\x1b[0m');
  console.log('   Vercel Dashboard → Your Project → Settings → Environment Variables');
  console.log('   (Use your production URL for NEXTAUTH_URL & NEXT_PUBLIC_SITE_URL)\n');
}

main().catch((err) => {
  console.error('\x1b[31mSetup failed:\x1b[0m', err.message);
  process.exit(1);
});
